config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }  
  devise_for :users, path: 'users' , controllers: { sessions: "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events
  resources :testimonials
  resources :articles

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user, optional: true
	mount_uploader :cover, FileUploader
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @min = Event.minimum(:day)
    @first_event = Event.where(day: @min).last()
    @events = Event.all 
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :cover, :location, :day, :time, :typeevent)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :typeevent %>
    <%= form.number_field :typeevent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<main>
  <div class="feed"> 
    <h2><%= @first_event.title %></h2>
    <img src="<%= @first_event.cover %>">
    <p><%= @first_event.description %></p>
    <p><%= link_to 'Conoce más', @first_event %></p>
  </div>
</main>

<section class="row">
    <% @events.each do |event| %>
      <div class="col">
        <h3><%= link_to event.title, event %></h3>
        <img src="<%= event.cover %>" />
        <p><%= event.description %></p>
        <p>Fecha: <%= event.day %></p>
        <p>Hora: <%= event.time.hour %> horas.</p>
        <p><%= link_to 'Conoce más', event %></p>
        <% if admin_signed_in? %>
        <p><%= link_to 'Editar', edit_event_path(event) %></p>
        <p><%= link_to 'Eliminar', event, method: :delete, data: { confirm: '¿Estás seguro?' } %></p>
        <% end %>
      </div>
    <% end %>  
</section>
<% if admin_signed_in? %>
<aside>

        <%= link_to 'Nuevo evento', new_event_path %>

</aside>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="details">
<h1>Asambleas y Eventos</h1>

<h2><%= @event.title %></h2>

<div class="cover">
    <img src="<%= @event.cover %>"/>
</div>

<div class="description">
  <p><%= @event.description %></p>
<p>Fecha: <%= @event.day %> Hora: <%= @event.time.hour %>:<%= @event.time.min %></p>
<p>Ubicación: <%= @event.location %></p>
</div>
</div>

<aside>
<%= link_to 'Asistir', edit_event_path(@event) %> 
</aside>
<aside>
<% if admin_signed_in? %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<% end %> 
<%= link_to 'Back', events_path %>
</aside>